---
title: "vdheights"
author: "Claire Tortorelli"
date: "August 17, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(nlme)
library(emmeans)
```

Read in data
```{r}
vdheights <- read.csv("C:\\Users\\cmtortor\\Box Sync\\OSU\\VEDU project\\SGH\\Analysis\\raw data\\2020_vd_heights-by-vegtype.csv")

#set vegtype to a factor
vdheights$vegtype <- factor(vdheights$vegtype, c("ARRI", "ARAR", "SEEP"))
```

model ventenata height response to vegetation type
```{r}

#model ventenata height response to vegtype
mheights <- lme(log(Height.cm) ~ vegtype, random = ~ 1|plotno/Plot, data = vdheights)

plot(mheights)
summary(mheights)

```

Compare means with emmeans
```{r}

(em <- emmeans(mheights, specs = pairwise ~ vegtype, type = "response"))
emdf <- data.frame(em$emmeans)

#reverse contrasts for to talk about heights being heigher rather than lwoer
(em2 <- emmeans(mheights, specs = revpairwise ~ vegtype, type = "response"))
#vd heights are 5cm lower in arar than seep plots and 7cm lower in arri than seep plots. 
confint(em2)
```

Explore contrasts
```{r}

em_dat = em$contrasts %>%
summary(infer = c(TRUE, FALSE) ) %>%
as.data.frame() %>%
   # select(-SE, -df) %>% # keep all columns other than SE, df
mutate_if(is.numeric, round, 2) # Round numeric columns to two digits

em_dat = mutate(em_dat, ci = paste(lower.CL, sprintf("%.2f", upper.CL), sep = ", ") )

em_dat = em_dat[,c(1,2,7)]

colnames(em_dat) = c("Comparison", "Ratio",
"95% CI")

#set comparisons
em_dat$Comparison <- factor(em_dat$Comparison, levels = c("ARRI / ARAR", "ARRI / SEEP", "ARAR / SEEP"), labels = c("ARRI / ARAR" = "scabland/low sage-steppe", "ARRI / SEEP" = "scabland/wet meadow", "ARAR / SEEP" = "low sage-steppe/ wet meadow"))

emdf$vegtype <- factor(emdf$vegtype, labels = c("ARRI"="scabland", "ARAR"="low sage-steppe", "SEEP" = "wet meadow"))

```

plot the means and confidence intervals
```{r fig.height=3, fig.width=3}
pal <- c("#A6761D", "#E6AB02" , "#666666")



( g1 = ggplot(emdf, aes(y = response, x = vegtype, color = vegtype)) +
# Define stock as group this week as well as set x and y axes
geom_point(position = position_dodge(width = .75), size = 3 ) + # Add points, dodge by group
geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL, width = 0.5), size = 1,
position = position_dodge(width = .75) ) + # Add errorbars, dodge by group
theme_bw(base_size = 14) +
labs(y = expression("mean"~italic("V. dubia")~" height"))+
scale_color_manual(values = pal))+
    guides(color = FALSE)+
theme(
panel.grid.minor = element_blank(),
axis.title.x=element_blank(),# Remove gridlines
panel.grid.major.x = element_blank() )


# ggsave("vdheights.png")
#ggsave("vdheights.svg")

```
